######################################################################################
 [error]
  File "/home/jake/Gits/ssd_tensorflow/train.py", line 36, in train
    run_train(dataset.map(resize_image, num_parallel_calls=tf.data.experimental.AUTOTUNE).batch(64).prefetch(tf.data.experimental.AUTOTUNE))
  File "/home/jake/Gits/ssd_tensorflow/train.py", line 22, in run_train
    predicted_locs, predicted_socres = model(image)# (N, 8732, 4), (N, 8732, n_classes)
  File "/home/jake/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/jake/Gits/ssd_tensorflow/model.py", line 39, in call
    x = self.conv1_1(x)
TypeError: 'tuple' object is not callable

def call(self,x):
    x = self.conv1_1(x)
    x = self.conv1_2(x)
    x = self.pool1(x)

[solution]

######################################################################################
[error]
File "/home/jake/venv/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 270, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/jake/venv/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Can't convert non-rectangular Python sequence to Tensor.

print(type(image), type(target))
<class 'tensorflow.python.framework.ops.EagerTensor'> <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'>

[solution]
boxes = tf.ragged.constant(boxes)
######################################################################################
